server:
  type: default
  maxThreads: 100

  applicationConnectors:
    - type: http
      port: 25380

  adminConnectors:
    - type: http
      port: 25381

  requestLog:
    appenders:
      - type: console

logging:

  level: DEBUG

  appenders:
    - type: console
      threshold: WARN
      target: stderr
